# Generated by Django 3.2.7 on 2022-10-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221029_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='Post',
        ),
    ]
