# Generated by Django 3.2.7 on 2022-10-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_post_rating_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='Post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
